import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";

import "./globals.css";
import NavBar from "@/components/ui/navBar";
import Keyboard from "@/components/ui/keyboard";
import Theme from "@/components/ui/theme";


const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});


export const metadata: Metadata = {
  title: "Blog Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} min-h-scree bg-gray-50`}>
     <NavBar/>


        {children}
      </body>
    </html>
  );
}
